apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-webhook
  labels:
    app: argo-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-webhook
  template:
    metadata:
      labels:
        app: argo-webhook
    spec:
      containers:
      - name: argo-webhook
        image: celfring/argo-ci
